version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env # Ensure this line is included to load the .env file
    depends_on:
      - redis
      - mongo
    networks:
      - quiz-network

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - quiz-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge
